ALLOWED_CONTENT_TYPES = ["image/jpeg", "image/png"]
MAX_UPLOAD_FILES = 10

UPLOAD_URL_EXPIRES_IN_SECONDS = 300
MAX_UPLOAD_FILE_SIZE_BYTES = 5 * 1024 * 1024  # 5 MB

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
